In [3]:
import pandas as pd
import numpy as np

In [4]:
pip install xlrd

Collecting xlrd
  Downloading https://files.pythonhosted.org/packages/b0/16/63576a1a001752e34bf8ea62e367997530dc553b689356b9879339cf45a4/xlrd-1.2.0-py2.py3-none-any.whl (103kB)
     |████████████████████████████████| 112kB 3.2MB/s eta 0:00:01
Installing collected packages: xlrd
Successfully installed xlrd-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
archivo = 'Datos_3.xlsm'
df = pd.read_excel(archivo)
df.head()

,Sample,Te_Verde,Te_Negro,Te_Mate,Te,Azucar,SCOBY,Liq_Ini,Brix_Ini,PH_Ini,Agua,Agua_disp,Temp,Tiempo,Brix_Out,PH_Out
0,1,1,0,0,10.0,90,797,0.3,4.0,2.8,3.0,3.3,15.4,1,3.8,3.0
1,2,0,1,0,10.0,90,930,0.3,3.8,2.7,3.0,3.3,15.5,1,3.0,3.4
2,3,0,0,1,10.0,90,839,0.3,4.0,2.5,3.0,3.3,15.5,1,3.0,3.1
3,4,1,0,0,10.0,180,772,0.3,4.0,2.8,3.0,3.3,15.7,1,5.5,3.3
4,5,0,1,0,10.0,180,737,0.3,3.8,2.7,3.0,3.3,15.4,1,5.5,3.4